name: Deploy Changes to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.AI_INSPIN_SERVER }}
        username: ${{ secrets.AI_INSPIN_USERNAME }}
        password: ${{ secrets.AI_INSPIN_PASSWORD }}
